### ISSUE TITLE
Actually add the headers.srcDirs based on includePaths

### ISSUE THREAD

**Issue by eljobe** [gradle/perf-native-large#12]
Every component has 1, 2, 3, or 4 includePaths.
- If there is only 1, it is Gradle’s default header path `src/<name>/headers`
- If there are 2, then, we add a directory with (all the headers?) `src/shared/headers`
- If it is a test component and there are 3, the 3rd one is the test infrastructure headers `src/<name>Test/headers`
- If it is a regular component and there are 3, or a test-component and there are 4, the last one is generated headers `src/<name>/generated_headers`

So, you might see:

```
model {
    components {
        goober(NativeLibrarySpec) {
            sources {
                cpp {
                    exportedHeaders {
                        srcDirs "src/goober/headers", "src/shared/headers", "src/goober/generated_headers"
                    }
                }
            }
        }
    }
    testSuites {
        gooberTest(GoogleTestTestSuite) {
            testing $.components.goober
            cpp {
                exportedHeaders {
                    srcDirs "src/goober/headers", "src/gooberTest/headers", "src/shared/headers"
                }
            }
        }
    }
}
```

About test directories
- The tests have two default directories and their conventional one. (?)
  I, @eljobe, think this means "two default directories": `src/goober/headers` and `src/gooberTest/headers` and "their conventional one" `src/shared/headers`
- There's not a test only include directory.  (?)
  I, @eljobe, think this means, there isn't something like `src/shared/test_headers`
- They only have their headers in one directory for a project. (?)
  I, @eljobe, think that this means all the headers for all the components in a project live in `$projectDir/shared/headers` instead of in the default-per-component headers directories like, `$projectDir/src/goober/headers`

Other constraints
- generated sources can be ignored and counted as headers or sources that exist (?)

About source and headers directories
- `src/component.name/cpp` for sources
- `src/component.name/headers` for headers
- The default includes are just the headers dir
- use conventional src and header locations even though the build to mimic doesn't do this (default conventions aren't used)
  I, @eljobe, think we should actually put the headers in a per-project shared directory, because it isn't very difficult to do correctly, and it more closely mirrors what is being done on the real project.

**Comment by lhotari** [comment]
I think that "conventional" directories are simply `src/component.name/cpp` and `src/component.name/headers`. I'll try to come up with something. 

I guess having real use of the include files in different components is important. I'm trying to understand how this all works. Does the include file name have to be unique?
